### ISSUE TITLE
Mode not changing to morning

### ISSUE THREAD

**Issue by pointlevel** [Pythm/ad-ModeManagement#4]
Hi,

I notice that normal mode is activated instead of the morning, when i believe morning is the one that should be activated.

Version: 0.1.6

```yaml
modeManage:
  module: modeManagement
  class: ModeManagement
  HALightModeText: input_text.lightmode
  workday: binary_sensor.workday_sensor
  turn_off_at_night:
    - input_boolean.stop_non_bedroom_sonos
  morning_sensors:
    - binary_sensor.master_bedroom_bedside_left_motion_sensor_occupancy
  morning_start_listen_time: "05:30:00"
  morning_to_normal: "09:00:00"
```
![Skärmbild 2024-11-12 072237](https://github.com/user-attachments/assets/4ee8cdbc-dbaf-49bc-b94b-395381680759)

**Comment by Pythm** [comment]
Is there anything in the logs at that time or when you initialize?

**Comment by pointlevel** [comment]
No, nothing in the logs at all.

**Comment by pointlevel** [comment]
Exactly the same this morning, the "binary_sensor.master_bedroom_bedside_left_motion_sensor_occupancy" detected motion at 05:50:28, and the night turned to normal at the exact same time. Workday On. No logs.

Complete config:

```yaml
modeManage:
  module: modeManagement
  class: ModeManagement
  HALightModeText: input_text.lightmode
  workday: binary_sensor.workday_sensor
  turn_off_at_night:
    - input_boolean.stop_non_bedroom_sonos
  morning_sensors:
    - binary_sensor.master_bedroom_bedside_left_motion_sensor_occupancy
  morning_start_listen_time: "05:30:00"
  morning_to_normal: "09:00:00"

  #night_sensors:
  night_start_listen_time: "22:00:00"
  execute_night_at: "02:00:00"

  presence:
    - person: person.me
      role: adult
    - person: person.girlfriend
      role: adult
    - person: person.child
      role: kid

  vacuum:
    - vacuum.bengan

  prevent_vacuum:
    - input_boolean.disable_auto_vacuum_cleaner
   
  # for future usage
  notify_reciever: notify.telegram_family
```
